# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/pb/server_sensors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/pb/server_sensors.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eserver/pb/server_sensors.proto\"_\n\x16sensor_reading_request\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x1b\n\x13reading_location_id\x18\x02 \x01(\t\x12\x15\n\rreading_value\x18\x03 \x01(\x02\"U\n\x17sensor_reading_response\x12\x12\n\nreading_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"2\n\x1csensor_reading_fetch_request\x12\x12\n\nreading_id\x18\x01 \x01(\t\"i\n\"sensor_reading_fetch_item_response\x12\x1b\n\x13sensor_reading_item\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x9f\x02\n\x13sensor_reading_item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x1b\n\x13reading_location_id\x18\x03 \x01(\t\x12\x15\n\rreading_value\x18\x04 \x01(\x02\x12\x17\n\x0ftrusted_reading\x18\x05 \x01(\x08\x12\x16\n\x0elocation_known\x18\x06 \x01(\x08\x12\x19\n\x11location_accurate\x18\x07 \x01(\x08\x12\x14\n\x0cis_processed\x18\x08 \x01(\x08\x12\x0f\n\x07read_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\x12\x13\n\x0breceived_at\x18\x0b \x01(\t\x12\x19\n\x11overall_integrity\x18\x0c \x01(\x02\"v\n\x1dsensor_reading_fetch_response\x12-\n\x0fsensor_readings\x18\x01 \x03(\x0b\x32\x14.sensor_reading_item\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x0e\n\x0cno_parameter2\xea\x01\n\rSensorService\x12\x43\n\x0csave_reading\x12\x17.sensor_reading_request\x1a\x18.sensor_reading_response\"\x00\x12?\n\x0cget_readings\x12\r.no_parameter\x1a\x1e.sensor_reading_fetch_response\"\x00\x12S\n\x0bget_reading\x12\x1d.sensor_reading_fetch_request\x1a#.sensor_reading_fetch_item_response\"\x00\x62\x06proto3'
)




_SENSOR_READING_REQUEST = _descriptor.Descriptor(
  name='sensor_reading_request',
  full_name='sensor_reading_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='sensor_reading_request.sensor_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading_location_id', full_name='sensor_reading_request.reading_location_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading_value', full_name='sensor_reading_request.reading_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=129,
)


_SENSOR_READING_RESPONSE = _descriptor.Descriptor(
  name='sensor_reading_response',
  full_name='sensor_reading_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading_id', full_name='sensor_reading_response.reading_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='sensor_reading_response.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='sensor_reading_response.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=216,
)


_SENSOR_READING_FETCH_REQUEST = _descriptor.Descriptor(
  name='sensor_reading_fetch_request',
  full_name='sensor_reading_fetch_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading_id', full_name='sensor_reading_fetch_request.reading_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=268,
)


_SENSOR_READING_FETCH_ITEM_RESPONSE = _descriptor.Descriptor(
  name='sensor_reading_fetch_item_response',
  full_name='sensor_reading_fetch_item_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_reading_item', full_name='sensor_reading_fetch_item_response.sensor_reading_item', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='sensor_reading_fetch_item_response.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='sensor_reading_fetch_item_response.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=375,
)


_SENSOR_READING_ITEM = _descriptor.Descriptor(
  name='sensor_reading_item',
  full_name='sensor_reading_item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sensor_reading_item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='sensor_reading_item.sensor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading_location_id', full_name='sensor_reading_item.reading_location_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading_value', full_name='sensor_reading_item.reading_value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trusted_reading', full_name='sensor_reading_item.trusted_reading', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location_known', full_name='sensor_reading_item.location_known', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location_accurate', full_name='sensor_reading_item.location_accurate', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_processed', full_name='sensor_reading_item.is_processed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_at', full_name='sensor_reading_item.read_at', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='sensor_reading_item.updated_at', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='received_at', full_name='sensor_reading_item.received_at', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overall_integrity', full_name='sensor_reading_item.overall_integrity', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=665,
)


_SENSOR_READING_FETCH_RESPONSE = _descriptor.Descriptor(
  name='sensor_reading_fetch_response',
  full_name='sensor_reading_fetch_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_readings', full_name='sensor_reading_fetch_response.sensor_readings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='sensor_reading_fetch_response.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='sensor_reading_fetch_response.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=785,
)


_NO_PARAMETER = _descriptor.Descriptor(
  name='no_parameter',
  full_name='no_parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=801,
)

_SENSOR_READING_FETCH_RESPONSE.fields_by_name['sensor_readings'].message_type = _SENSOR_READING_ITEM
DESCRIPTOR.message_types_by_name['sensor_reading_request'] = _SENSOR_READING_REQUEST
DESCRIPTOR.message_types_by_name['sensor_reading_response'] = _SENSOR_READING_RESPONSE
DESCRIPTOR.message_types_by_name['sensor_reading_fetch_request'] = _SENSOR_READING_FETCH_REQUEST
DESCRIPTOR.message_types_by_name['sensor_reading_fetch_item_response'] = _SENSOR_READING_FETCH_ITEM_RESPONSE
DESCRIPTOR.message_types_by_name['sensor_reading_item'] = _SENSOR_READING_ITEM
DESCRIPTOR.message_types_by_name['sensor_reading_fetch_response'] = _SENSOR_READING_FETCH_RESPONSE
DESCRIPTOR.message_types_by_name['no_parameter'] = _NO_PARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sensor_reading_request = _reflection.GeneratedProtocolMessageType('sensor_reading_request', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_REQUEST,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_request)
  })
_sym_db.RegisterMessage(sensor_reading_request)

sensor_reading_response = _reflection.GeneratedProtocolMessageType('sensor_reading_response', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_RESPONSE,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_response)
  })
_sym_db.RegisterMessage(sensor_reading_response)

sensor_reading_fetch_request = _reflection.GeneratedProtocolMessageType('sensor_reading_fetch_request', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_FETCH_REQUEST,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_fetch_request)
  })
_sym_db.RegisterMessage(sensor_reading_fetch_request)

sensor_reading_fetch_item_response = _reflection.GeneratedProtocolMessageType('sensor_reading_fetch_item_response', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_FETCH_ITEM_RESPONSE,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_fetch_item_response)
  })
_sym_db.RegisterMessage(sensor_reading_fetch_item_response)

sensor_reading_item = _reflection.GeneratedProtocolMessageType('sensor_reading_item', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_ITEM,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_item)
  })
_sym_db.RegisterMessage(sensor_reading_item)

sensor_reading_fetch_response = _reflection.GeneratedProtocolMessageType('sensor_reading_fetch_response', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR_READING_FETCH_RESPONSE,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:sensor_reading_fetch_response)
  })
_sym_db.RegisterMessage(sensor_reading_fetch_response)

no_parameter = _reflection.GeneratedProtocolMessageType('no_parameter', (_message.Message,), {
  'DESCRIPTOR' : _NO_PARAMETER,
  '__module__' : 'server.pb.server_sensors_pb2'
  # @@protoc_insertion_point(class_scope:no_parameter)
  })
_sym_db.RegisterMessage(no_parameter)



_SENSORSERVICE = _descriptor.ServiceDescriptor(
  name='SensorService',
  full_name='SensorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=804,
  serialized_end=1038,
  methods=[
  _descriptor.MethodDescriptor(
    name='save_reading',
    full_name='SensorService.save_reading',
    index=0,
    containing_service=None,
    input_type=_SENSOR_READING_REQUEST,
    output_type=_SENSOR_READING_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_readings',
    full_name='SensorService.get_readings',
    index=1,
    containing_service=None,
    input_type=_NO_PARAMETER,
    output_type=_SENSOR_READING_FETCH_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_reading',
    full_name='SensorService.get_reading',
    index=2,
    containing_service=None,
    input_type=_SENSOR_READING_FETCH_REQUEST,
    output_type=_SENSOR_READING_FETCH_ITEM_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORSERVICE)

DESCRIPTOR.services_by_name['SensorService'] = _SENSORSERVICE

# @@protoc_insertion_point(module_scope)
